# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # Standard Docker network for HA add-ons

homeassistant:
  packages: !include_dir_named packages

rest_command:
  send_guidebook_update_prod:
    url: "https://manual.195vbr.com/api/ha-webhook"
    method: "POST"
    headers:
      content-type: "application/json"
      x-webhook-secret: !secret ha_webhook_secret
    payload: '{"house": "{{ house }}", "entity_id": "{{ entity_id }}", "state": "{{ state }}", "attributes": {{ attributes }} }'
